{
 "title": "Hue",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bulb",
    "query": "label_values(hue_bulb_status, bulb)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bridge",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hue_status" }
   ]
  },
  {
   "title": "Sleep Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "hue_sleep_time " }
   ]
  },
  {
   "title": "Last check",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "time() - hue_last_check" }
   ]
  },
  {
   "title": "$bulb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "repeat": "bulb",
   "targets": [
    {
     "expr": "hue_bulb_status{bulb=\"$bulb\"}"
    }
   ]
  }
 ]
}